language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install tox tox-travis"
# command to run tests
script:
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" KalturaClient/tests/config.template.ini > KalturaClient/tests/config.ini
    - tox
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Noam.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always
