language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: python -m unittest discover 
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Noam.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always
